---
- hosts: mysql
  roles:
    - ten7.flightdeck_base
  tasks:
    - name: Install needed software.
      apk:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - "py3-mysqlclient"
        - "mariadb"
        - "mariadb-client"
      notify:
        - clear apk cache
    - name: Install build deps
      shell: >
        apk add --virtual build-deps
        gcc
        libffi-dev
        python3-dev
        linux-headers
        musl-dev
        openssl-dev
        rust
        cargo
      notify: remove build deps
    - name: Install the additional packages from pip
      pip:
        name:
          - "boto3"
          - "botocore"
        extra_args: "--ignore-installed --no-cache-dir"
    - name: Ensure key directories are owned by mysql
      file:
        path: "{{ item }}"
        state: directory
        owner: "mysql"
        group: "mysql"
        mode: "u=rwx,g=rwx,o=r"
        recurse: yes
      loop:
        - "/var/lib/mysql"
        - "/var/run/mysqld"
        - "/etc/mysql"
        - "/etc/my.cnf.d"
    - name: Ensure key files are owned by mysql
      file:
        path: "{{ item }}"
        state: file
        owner: "mysql"
        group: "mysql"
      loop:
        - "/etc/my.cnf"

  handlers:
    - name: remove build deps
      shell: >
        apk del build-deps
    - name: clear apk cache
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/*"
        - "/var/cache/apk/*"
